services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - PUID=$user
      - PGID=$user
      - TZ=Europe/Helsinki
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${HOME}/homeassistant:/config
      - /var/run/dbus:/var/run/dbus:ro
    ports:
      - 8123:8123
    restart: unless-stopped

  hass-configurator:
    container_name: hassconf
    image: docker.io/causticlab/hass-configurator-docker
    restart: unless-stopped
    ports:
      - "3218:3218/tcp"
    volumes:
      - ${HOME}/hassconf/config:/config
      - ${HOME}/homeassistant:/hass-config
      - ${HOME}/compose.yaml:/hass-config/compose.yaml
    depends_on:
      - homeassistant